ecommerceproject/cart/urls.py
from django.urls import path
from .import views
app_name='cart'
urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove')

]

ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shop.urls',namespace='shop')),
    path('search/',include('searchapp.urls')),
    path('cart/',include('cart.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerceproject/searchapp/urls.py
from django.urls import path
from .import views
app_name='searchapp'
urlpatterns = [
    path('',views.searchresult,name='searchresult'),

]

ecommerceproject/shop/urls.py
from django.urls import path
from .import views
app_name='shop'
urlpatterns = [
    path('',views.allprodcat,name='allprodcat'),
    path('<slug:c_slug>/',views.allprodcat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.prodetail,name='procatdetail')
]

ecommerceproject/cart/models.py
from django.db import models
from shop .models import product
# Create your models here.
class carts(models.Model):
      cart_id=models.CharField(max_length=250,blank=True)
      date_added=models.DateField(auto_now_add=True)

      class Meta:
            db_table='cart'
            ordering=['date_added']

      def __str__(self):
          return '{}'.format(self.cart_id)

class cart_item(models.Model):
      product2=models.ForeignKey(product,on_delete=models.CASCADE)
      Cart = models.ForeignKey(carts, on_delete=models.CASCADE)
      quantity=models.IntegerField()
      active=models.BooleanField(default=True)
      class Meta:
            db_table='cart_item'
      def subtotal(self):
          return self.product2.price * self.quantity
      def __str__(self):
            return '{}'.format(self.product2)

ecommerceproject/shop/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc1=models.TextField(blank=True)
    img=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('shop:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    img = models.ImageField(upload_to='product',blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(category,on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('shop:procatdetail',args=[self.category.slug,self.slug])

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

    def __str__(self):
        return '{}'.format(self.name)

ecommerceproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop .models import product
from .models import carts,cart_item
from django.core.exceptions import ObjectDoesNotExist
def cart_id(request):
    Cart = request.session.session_key
    if not Cart:
        Cart = request.session.create()
    return Cart

def add_cart(request,product_id):
    product2 = product.objects.get(id=product_id)
    try:
        Cart = carts.objects.get(cart_id=cart_id(request))
    except carts.DoesNotExist:
        Cart = carts.objects.create(cart_id=cart_id(request))
        Cart.save()
    try:
        Cart_item=cart_item.objects.get(product2=product2,Cart=Cart)
        if Cart_item.quantity < Cart_item.product2.stock:
           Cart_item.quantity += 1
           Cart_item.save()
    except cart_item.DoesNotExist:
        Cart_item = cart_item.objects.create(
            product2=product2,
            quantity=1,
            Cart=Cart)
        Cart_item.save()

    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
       Cart=carts.objects.get(cart_id=cart_id(request))
       cart_items=cart_item.objects.filter(Cart=Cart,active=True)
       for  Cart_item in cart_items:
            total+=( Cart_item.product2.price *  Cart_item.quantity)
            counter+= Cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    Cart=carts.objects.get(cart_id=cart_id(request))
    product2=get_object_or_404(product,id=product_id)
    Cart_item=cart_item.objects.get(product2=product2,Cart=Cart)
    if Cart_item.quantity > 1:
        Cart_item.quantity -= 1
        Cart_item.save()
    else:
        Cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    Cart = carts.objects.get(cart_id=cart_id(request))
    product2 = get_object_or_404(product, id=product_id)
    Cart_item = cart_item.objects.get(product2=product2, Cart=Cart)
    Cart_item.delete()
    return redirect('cart:cart_detail')

ecommerceproject/searchapp/views.py
from django.shortcuts import render
from shop .models import product
from django.db.models import Q
# Create your views here.
def searchresult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = product.objects.filter(Q(name__contains=query) | Q(desc__contains=query))
    return render(request,'search.html',{'query':query,'products':products})

ecommerceproject/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import category,product
from django.core.paginator import Paginator,EmptyPage,InvalidPage

def allprodcat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(category,slug=c_slug)
        products_list=product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=product.objects.all().filter(available=True)
    paginator=Paginator(products_list,8)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    return render(request,'category.html',{'c_page':c_page,'products':products})

def prodetail(request,c_slug,product_slug):
    try:
        product1=product.objects.get(category__slug=c_slug,slug=product_slug)
        related_products = product.objects.filter(category__slug=c_slug).exclude(slug=product_slug)[:4]
    except Exception as e:
        raise e
    context = {
        'product1': product1,
        'related_products': related_products,
        'product': product1,  # pass product1 to the template context as product
    }
    return render(request,'product.html',context)

ecommerceproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bruno+Ace+SC&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://kit.fontawesome.com/03e91b3982.js" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}" >
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container-fluid">
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
</div>
    {% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>

ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

This is cart page proceed if you are ready to order

{% endblock %}
{% block title %}
    Cart
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your Food cart is empty</h1>
        <br>
        <p class="text-center">Please click <a href="{% url 'shop:allprodcat' %}" class="btn btn-link btn-sm">Here</a>To continue shopping </p>


    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title"><b>Your Food Cart</b></h1>
        <br>

    </div>
</div>
<div class="row mx_auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_table">
            <thead class="my_thead">
            <tr>
                <th colspan="5">Your Items</th>
            </tr>
            </thead>
            <tbody>
            {% for  Cart_item in cart_items %}
            <tr>
                <td>
                    <a href="{{ Cart_item.product2.get_absolute_url }}"><img src="{{ Cart_item.product2.img.url }}" alt="" class="float-left rounded custom_img" style="width:200px"></a>
                </td>
                <td class="text-justify">
                    <br>
                    {{ Cart_item.product2.name}}
                    <br>
                    SKU: {{ Cart_item.product2.id}}
                    <br>
                    Price:Rs{{ Cart_item.product2.price}}
                    <br>
                    Qty: {{ Cart_item.quantity}} * Rs {{ Cart_item}}
                    <br>
                </td>
                <td>
                    Rs {{ Cart_item.subtotal}}
                </td>
                {% if  Cart_item.quantity < Cart_item.product2.stock %}
                <td>
                    <a href="{% url 'cart:add_cart'  Cart_item.product2.id %}" class="custom_a" ><i class="fa-regular fa-square-plus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cart:cart_remove' Cart_item.product2.id %}" class="custom_a"><i class="fa-regular fa-square-minus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cart:full_remove' Cart_item.product2.id %}" class="custom_a"><i class="fa-solid fa-trash-can custom_icon"></i></a>
                </td>
                {% else %}
                <td>
                    &nbsp;<a href="{% url 'cart:cart_remove' Cart_item.product2.id %}" class="custom_a"><i class="fa-regular fa-square-minus"></i></a>
                    &nbsp;<a href="{% url 'cart:full_remove' Cart_item.product2.id %}" class="custom_a"><i class="fa-solid fa-trash-can"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="my_table">
            <thead class="my_thead">
            <tr>
                <th>
                    Checkout Here
                </th>
            </tr>
            </thead>

            <tbody>
            <tr>
                <td>
                    <br>Please go through your order once more and finalize it
                </td>
            </tr>
            <tr>
                <td class="text-left">
                    Your Total is: <strong>{{ total }}</strong>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="d-grid gap-2">
            <a href="{% url 'shop:allprodcat' %}" class="btn btn-info btn-block btn-sm">Continue Shopping</a>
        </div><br>
        <div class="d-grid gap-2">
            <a href="{% url 'shop:allprodcat' %}" class="btn btn-success btn-block btn-sm">Payment</a>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if c_page %}
      {{c_page.description|truncatewords:155}}
    {% else %}
         Welcome to PomPom Store here you can buy any items with discount
    {% endif %}
{% endblock %}

{% block title %}
    {% if c_page %}
      {{c_page.name}} - PomPom Store
    {% else %}
         our new collections are added go through them - PomPom Store
    {% endif %}
{% endblock %}

{% block content %}
   {% if c_page %}
    <div>
        <div class="row my_row_class">
            <div class="mx_auto">
        <p><a href="{% url 'shop:allprodcat' %}">PomPom Store</a></p>
        </div>
    </div>
    </div>
    {% endif %}
    <div class="mx_auto">
        {% if c_page %}
        <img class="my_image" src="{{c_page.img.url}}" alt="{{category.name}}">
    </div>
      <br>
    <div>
        <h1 class="text-center  my_title">{{c_page.name}}</h1>
        <p class="text-center">{{c_page.desc1}}</p>
    </div>
    {% else %}
    <div>
    <img class="my_image my_image_padding" src="{% static 'img/banner1.png' %}" alt="our products" width="1450px">
    </div>
    <br>
     <div>
         <h1 class="text-center my_title">Our Highlights</h1>
         <p class="text-center  ">Juicy, ripe and bursting with flavor - our fresh fruits are hand-picked daily to ensure maximum freshness and taste.
             From crisp apples to succulent strawberries, our fruit selection is sure to satisfy any craving for something sweet and healthy.
             Experience the taste of nature's candy with our selection of luscious fruits, all sourced from trusted local and international growers.
             Looking for a healthy snack on-the-go? Grab one of our pre-cut fruit cups, packed with a variety of your favorite fruits for a delicious and convenient treat.
             Indulge in the taste of summer all year round with our tropical fruit selection, featuring exotic delights like mangoes, pineapples, and papayas.
             From antioxidant-rich berries to vitamin-packed citrus, our fruits are not only delicious but also packed with essential nutrients to help you stay healthy and energized.
             Bring a pop of color and flavor to your next meal with our vibrant and delicious fruit options, perfect for adding a touch of sweetness to any dish.
             Whether you're in the mood for a refreshing smoothie or a classic fruit salad, our fruit selection is versatile and perfect for all your culinary adventures.</p>
     </div>
    {% endif %}
    <div class="container-fluid">
        <div class="row mx_auto">
            {% for product in products.object_list %}
        <div class="my_bottom_margin  col-md-4  col-lg-3  row row-cols-4 mt-5 col-sm-5 offset-sm-2 col-md-6 offset-md-0 ">
            <div class="card text-center" style="min-width:18rem;">
            <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.img.url}}" alt="{{product.name}}" width="500px"></a>
            <div class="card-body">
                <h2>{{product.name}}</h2>
                <h4><p>{{product.price}}</p></h4>
            </div>
        </div>
    </div>
        {% endfor %}
    </div>
        <div class="mx_auto">
            {% if products.paginator.num_pages > 1 %}

            <hr>
            <div class="text-center">
                {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}}">{{pg}}</a>
                {% endfor %}

            </div>
            {% endif %}
        </div>
        <br>
</div>
{% endblock %}

ecommerceproject/templates/footer.html
<br><div class="footer navbar-fixed-bottom  my_footer">
    <p style="text-align: center">&copy;PomPom Store Pvt Ltd.All Rights Reserved</p>
</div>

ecommerceproject/templates/header.html
{% load static %}
<header>
  <center>
    <a href="{% url 'shop:allprodcat' %}"><img src="{% static 'img/logo1.png' %}" alt="logoimage" width="200px" height="200px"></a>
  </center>
</header>

ecommerceproject/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:allprodcat' %}">PomPom Store</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Menu
          </a>
          <ul class="dropdown-menu {% if sop in request.path %} active {% endif %}" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shop:allprodcat' %}">All products here</a></li>
            {% for category in links %}
            <li><a class="dropdown-item" href="{{category.get_url}}">{{category.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}" tabindex="-1" aria-disabled="true"><i class="fa-solid fa-cart-shopping"></i> ({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'searchapp:searchresult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
      </form>
    </div>
  </div>
</nav>

ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

      {{product1.description|truncatewords:155}}

{% endblock %}

{% block title %}
    {% if c_page %}
      {{product1.name}} - PomPom Store

    {% endif %}
{% endblock %}

{% block content %}
<div class="row my_product_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'shop:allprodcat' %}">Home</a> | <a href="{{product1.category.get_url}}">{{product1.category}}</a>|{{product1.name}}</p>
    </div>
</div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{product1.img.url}}" alt="{{product1.name}}" width="400px">
        </div>
    </div>
        <div class="col-12 col-sm-12-col-md-12 col-lg-6 text-justify">
            <div>
            <h1 class="my_prod_title">{{product1.name}}</h1>
            <p>Rs {{product1.price}}</p>
            <p class="my_title">Product Description</p>
            <p class="text-justify my_product_text">{{product1.desc}}</p>
            {% if product1.stock <= 0 %}
            <p class="text-justify my_product_text"><b>Sorry Out Of Stock Will soon Restore</b></p>
            {% else %}
            <a  class="btn btn-success" href="{% url 'cart:add_cart' product.id %}">ADD TO CART</a>
            {% endif %}

        </div>
    </div>
</div>
</div>
{% endblock %}

ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

         Welcome to PomPom Store here you can buy any items with discount

{% endblock %}
{% block title %}
    Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search">You Have Searched For : <b>"{{ query }}"</b></p>
</div>
<div class="container-fluid">
        <div class="row mx_auto">
            {% for product in products %}
        <div class="my_bottom_margin  col-md-4  col-lg-3  row row-cols-4 mt-5 col-sm-5 offset-sm-2 col-md-6 offset-md-0 ">
            <div class="card text-center" style="min-width:18rem;">
            <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.img.url}}" alt="{{product.name}}" width="500px"></a>
            <div class="card-body">
                <h2>{{product.name}}</h2>
                <h4><p>{{product.price}}</p></h4>
            </div>
        </div>
    </div>

 {% empty %}
            <div class="row mx_auto">
                <p class="text-center my_search"><b>No results found</b></p>
            </div>
 {% endfor %}
        </div>
</div>
{% endblock %}